services:
  - type: web
    name: Flask-Autocorrect-App
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 8080
